"""Poker math done locally: Monte Carlo equity, pot odds, preflop hand ranking."""

from __future__ import annotations

import random

from treys import Card, Evaluator

import cards

_EVALUATOR = Evaluator()
_DECK = [r + s for r in cards.RANKS for s in cards.SUITS]

# 169 starting hands, strongest first. Generated by simulating each hand against
# one random hand (40000 runs each). A starting point for ranges, not solver output.
PREFLOP_ORDER = (
    "AA KK QQ JJ TT 99 88 AKs 77 AQs AJs AKo ATs AQo AJo KQs 66 ATo A9s KJs A8s KTs A7s KQo "
    "A9o K9s QJs 55 KJo KTo A5s A8o A6s A4s QTs A7o K8s QJo A3s Q9s A6o K7s QTo JTs A5o K9o "
    "A2s 44 K6s A4o Q8s K8o A3o K5s Q9o J9s A2o K7o JTo K4s Q7s K6o K3s T9s Q6s J8s 33 K5o "
    "J9o Q8o K2s Q5s J7s K4o Q4s Q7o T8s T9o J8o K3o Q3s J6s Q6o T7s 98s K2o 22 Q2s J5s T8o "
    "Q5o J7o J4s Q4o T6s 97s J3s 98o T7o Q3o 87s J6o Q2o T5s J2s J5o 96s T4s 97o 86s T6o 95s "
    "J4o 76s T3s T2s 87o J3o 85s 96o J2o T5o T4o 75s 94s 86o 93s 65s 84s 76o 92s T3o 95o 74s "
    "T2o 64s 85o 83s 54s 82s 94o 75o 73s 65o 93o 53s 92o 84o 43s 63s 74o 54o 72s 83o 52s 62s "
    "64o 42s 82o 73o 53o 63o 32s 43o 72o 62o 52o 42o 32o"
).split()


def _combos(hand_class: str) -> int:
    if len(hand_class) == 2:
        return 6
    return 4 if hand_class.endswith("s") else 12


def _build_percentiles() -> dict[str, float]:
    result, seen = {}, 0
    for hand in PREFLOP_ORDER:
        seen += _combos(hand)
        result[hand] = seen / 1326
    return result


_PERCENTILE = _build_percentiles()


def preflop_percentile(hand_class: str | None) -> float | None:
    """Share of all starting hands that are at least as strong (0.005 = AA, 1.0 = worst)."""
    return _PERCENTILE.get(hand_class) if hand_class else None


def equity(hero: list[str], board: list[str], opponents: int = 1,
           iterations: int = 8000, rng: random.Random | None = None) -> float | None:
    """Win share (ties split) against `opponents` random hands. None if the cards are invalid."""
    if not cards.valid_deal(hero, board):
        return None
    opponents = max(1, min(int(opponents), 8))
    rng = rng or random
    hero_cards = [Card.new(c) for c in hero]
    board_cards = [Card.new(c) for c in board]
    rest = [Card.new(c) for c in _DECK if c not in hero and c not in board]
    missing = 5 - len(board_cards)
    need = missing + 2 * opponents

    won = 0.0
    for _ in range(iterations):
        draw = rng.sample(rest, need)
        full_board = board_cards + draw[:missing]
        mine = _EVALUATOR.evaluate(full_board, hero_cards)
        best, ties = mine, 0
        for i in range(opponents):
            score = _EVALUATOR.evaluate(full_board, draw[missing + 2 * i: missing + 2 * i + 2])
            if score < best:
                best = score
                break
            if score == mine:
                ties += 1
        if best == mine:
            won += 1.0 / (1 + ties)
    return won / iterations


def required_equity(pot: float | None, to_call: float | None) -> float | None:
    """Equity needed to call profitably. `pot` is the pot as shown, including the bet to call."""
    if not to_call:
        return 0.0
    if pot is None or pot < 0:
        return None
    return to_call / (pot + to_call)
